### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by jculverwell** [bodiddlie/rxheroes#1]
Thank you for this code and your article.  Any thoughts on how you would best display error messages arising from the http calls in the service?

**Comment by bodiddlie** [comment]
I would create actions/state/reducers for error messages. You could then dispatch actions that add an error message when your effects are running. Something like:

```
@Effect() loadHeroes$ = this.update$
  .ofType(HeroActions.LOAD_HEROES)
  .switchMap(() => this.svc.getHeroes()
    .map(heroes => this.heroActions.loadHeroesSuccess(heroes))
    .catch(err => this.errorActions.addErrorMessage(err));
  );
```

Then have some component that observes the error messages and deal with them accordingly. Just an idea.
