### ISSUE TITLE
Why json-server

### ISSUE THREAD

**Issue by jaichandra** [bodiddlie/rxheroes#5]
Thanks for putting up this example using ngrx. I am trying to pick a few concepts for here and figured that you are using `json-server` instead of `angular-in-memory-web-api`. Is there a specific reason for choosing this over the other? Would be very helpful if you could provide some thoughts.

**Comment by bodiddlie** [comment]
When I wrote this, I don't think `angular-in-memory-web-api` existed yet. It seems interesting, but on first glance, I think I would still go with `json-server`. It looks like you have to write some code that gets injected into your App Module for this to work. With json-server, it's a standalone thing that runs separate of the client code. Then I can just point the http calls to the relevant URL and go. Really just comes to down to a matter of taste. I prefer the simplicity of json-server. Good luck!

**Comment by jaichandra** [comment]
Thanks @bodiddlie :)
